image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
build_script:
- cmd: powershell -Command .\build.ps1 --currentBranch=%APPVEYOR_REPO_BRANCH% --nugetApiKey=%NUGET_API_KEY%
test_script:
- cmd: echo "test_script -> NOOP (tests are performed in cake script)"
after_test:
- cmd: echo "after_test -> NOOP (packaging is performed in cake script)"